### ISSUE TITLE
Compile Error document/new not compatible with interface declaration DocumentInterface::setCreatedAt(?DateTime $createdAt = NULL)

### ISSUE THREAD

**Issue by ionics** [webeweb/edm-bundle#1]
Compile Error: Declaration of WBW\Bundle\EDMBundle\Model\AbstractDocument::setCreatedAt(?DateTime $createdAt) must be compatible with WBW\Bundle\EDMBundle\Model\DocumentInterface::setCreatedAt(?DateTime $createdAt = NULL)

**Comment by webeweb** [comment]
Hi,

Give us some details ! Actually, it's complicated to understand what you do with this package in development.

Best regards

**Comment by ionics** [comment]
Sorry for the noise. I see, you marked compatible with PHP 7.0 "only" and this issue arises with 7.0+ (7.2,7.3,...) 
Fixed by adding return types to (by interface) contracted methods like:


```
    /**
     * {@inheritdoc}
     */
-  public function getAlphabeticalTreeNodeLabel(){
+  public function getAlphabeticalTreeNodeLabel() : string {
        return $this->getName();
    }

    /**
     * {@inheritdoc}
     */
-     public function getAlphabeticalTreeNodeParent(){
+    public function getAlphabeticalTreeNodeParent() : ?AlphabeticalTreeNodeInterface {
        return $this->parent;
    }
```


Kind regards,
Raphael
